---
category: Wikimedia Hackathon Athens 2023
description: Hacking room at the Wikimedia Hackathon 2023 in Athens.
directory_path: /home/lubianat/Pictures/2023/05 - May/wmhack23/keep/hacking room
title: Wikimedia Hackathon 2023 - Hacking Room - Day 1
user_name: TiagoLubiana