---
category: Aerial photographs from planes over Brazil from CGH to SDU
description: Aerial photographs of the flight between São Paulo and Rio de Janeiro, from the CGH to the SDU airport.
directory_path: /home/lubianat/Pictures/CGH
title: CGH to SDU flight in 2024
user_name: TiagoLubiana